apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-app-config
data:
  app.js: |
    const express = require('express');
    const app = express();
    const port = 8080;
    app.get('/', (req, res) => {
      res.send('Hello, Node.js from Kubernetes!');
    });
    app.listen(port, () => {
      console.log(`Node.js app listening at http://localhost:${port}`);
    });
